version: '3.8'

services:
  # Servicio de base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: softgenix
      POSTGRES_PASSWORD: s12345678
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servicio de aplicación Laravel (backend PHP)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - postgres

  # Servicio del servidor web Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pgdata:
